[build]
builder = "nixpacks"
buildCommand = "dotnet restore && dotnet build -c Release && dotnet publish -c Release -o output"

[deploy]
startCommand = "dotnet output/APS.dll"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:${PORT}" 